name: ignitenodejs2023modulo03

services:
  pg:
    image: bitnami/postgresql:16.4.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=petshop